# if dont want to mess with your os env
version: '3.1'
services:
  login:
    build:
      context: ./
      dockerfile: Dockerfile.local
    restart: always
    depends_on:
      - db
    environment:
      db_name: login
      db_username: root
      db_password: IIIdevops123!
      db_host: db
    ports:
      - 3000
  db:
    image: bitnami/mariadb:10.5
    restart: always
    environment:
      MARIADB_DATABASE: login
      MARIADB_ROOT_PASSWORD: IIIdevops123!
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080